add definition of junkie
tatianamac/selfdefined pull request #266
Opened 2020-08-03 17:43 UTC by calesennett

- Adds definition of `junkie`
- Adds `junkie` as ableist language
- Updated vulnerable `npm` packages

2020-08-21 16:21 UTC, tatianamac commented
Thank you for submitting, @calesennett and my apologies for taking so long to respond! I've put this out to the Self-Defined community on Slack to see if someone who has experienced the negative impact of this term could provide a review!

2020-08-22 16:30 UTC, kkemple requested changes
Thank you so much for the PR @calesennett! 💖

As someone who suffers from drug addiction and has been called a junkie, I've very happy to see this added to self defined. I've made some suggestions on the wording around the terminology for drug addict and some smaller suggestions around the issue definition. Would love to hear your thoughts!

Once again, thank you for submitting this PR!

2020-08-22 16:30 UTC, kkemple commented on 11ty/definitions/junkie.md
> +a drug addict. a person with a compulsive habit or obsessive dependency on something.
```suggestion
a drug addict. a person who suffers from a complex disease of the brain and body that involves compulsive use of one or more substances despite serious health and social consequences.
```

2020-08-22 16:30 UTC, kkemple commented on 11ty/definitions/junkie.md
> +a drug addict. a person with a compulsive habit or obsessive dependency on something.
I've updated the definition of an addict to reflect the latest terminology that focuses on addiction as a disease.

2020-08-22 16:30 UTC, kkemple commented on 11ty/definitions/junkie.md
> +Junkie is commonly used as a term for someone whose enthusiasm or zeal for something is extreme or beyond normal limits. However, this diminishes the seriousness of drug addiction and substance use d
```suggestion
Junkie is commonly used as a term for someone whose enthusiasm or zeal for something may be considered extreme or beyond normal interest by others. However, this diminishes the seriousness of drug addiction and substance use disorder.
```

2020-08-22 16:30 UTC, kkemple commented on 11ty/definitions/junkie.md
> +Junkie is commonly used as a term for someone whose enthusiasm or zeal for something is extreme or beyond normal limits. However, this diminishes the seriousness of drug addiction and substance use d
removing "is" as that states fact where this really falls under opinion

2020-08-27 22:51 UTC, tatianamac commented
@calesennett  Do you have bandwidth to address @kkemple 's suggestions? (No rush on our side; I just like to keep tasks moving.)

2020-09-02 18:11 UTC, calesennett commented
@kkemple Thanks for suggesting better language around the definition and issue with using this word. I've updated the language as well as brought in the most recent `prod` branch. Thanks so much!

2020-09-02 19:28 UTC, tatianamac commented on 11ty/definitions/junkie.md
> +slug: 'junkie'
```suggestion
slug: junkie
```

2020-09-02 19:29 UTC, tatianamac commented on 11ty/definitions/junkie.md
> +alt_words:
```suggestion
excerpt: a drug addict. a person who suffers from a complex disease of the brain and body that involves compulsive use of one or more substances despite serious health and social consequences.
```

2020-09-02 19:35 UTC, tatianamac approved these changes
Added some semantic/syntax edits, which I wish I would have caught before. I tried to rely heavily on suggestions so you can add/reject seamlessly—hopefully it's not a burden! Thank you so much for submitting this definition!

2020-09-02 19:35 UTC, tatianamac commented on 11ty/definitions/junkie.md
> +  text: 'ableist language'
```suggestion
  text: 'ableist language'
  excerpt: a drug addict. a person who suffers from a complex disease of the brain and body that involves compulsive use of one or more substances despite serious health and social consequences.
```

2020-09-02 19:35 UTC, tatianamac commented on 11ty/definitions/junkie.md
> +  - geek
```suggestion
alt_words:
  - aficionado
  - buff
  - fanatic
  - enthusiast
  - fiend
  - geek
  - lover
```

2020-09-02 19:35 UTC, tatianamac commented on 11ty/definitions/junkie.md
> +a drug addict. a person who suffers from a complex disease of the brain and body that involves compulsive use of one or more substances despite serious health and social consequences.
```suggestion
a drug addict; a person who suffers from a complex disease of the brain and body that involves compulsive use of one or more substances despite serious health and social consequences
```

2020-09-02 20:48 UTC, merged